markdown: rdiscount
auto: true
lsi: true
pygments: true

#haml: true
#sass: true
#post_defaults:
#  layout: post
#  author: code_monkey_steve

permalink: /:year/:month/:title.html
url: http://finagle.org
exclude: lib spec vendor views  Gemfile Gemfile.lock Rakefile config.ru lucid finagle.kdev4 comics.rb

